export const BASE_URL = "https://jiranew.cybersoft.edu.vn/api/";
export const TOKEN_CYBERSOFT =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5Mb3AiOiJCb290Y2FtcCA2MyIsIkhldEhhblN0cmluZyI6IjE2LzEwLzIwMjQiLCJIZXRIYW5UaW1lIjoiMTcyOTAzNjgwMDAwMCIsIm5iZiI6MTY5Njg3MDgwMCwiZXhwIjoxNzI5MTg0NDAwfQ._HrEe-Nmfst4upbWtIGcUIJ6CIbknZMHAlp8JbVhlRA";
